# azure-pipelines.yml
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  SSH_USER: 'user1'                  # change
  SSH_HOST: '135.235.136.171'                # change
  SSH_PORT: '22'                      # optional
  REMOTE_CMD: 'uname -a'              # your single command
  

steps:
  # 1) Pick your Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'   # or 3.11/3.10 as needed

  # 2) Install deps (if any)
  - script: |
      python -m pip install --upgrade pip
      pip install psutil    
      pip install pyotp
      pip install requests
      pip install Crypto
      pip install "pycryptodome>=3.20"
    displayName: 'Install dependencies'

  # 3) Run Python, capture stdout in a Bash variable, set a pipeline variable
  
  - bash: |      
      set -euo pipefail
    while IFS='=' read -r k v; do
      [ -z "${k:-}" ] && continue
      echo "##vso[task.setvariable variable=${k}]${v}"
    done < <(python arconazplugin.py lCpGj6G+cuuNQbA4cIWcBy8Cia4umkN1/ZovDWBmO22vH3MUR/sjTjzOzV1gfKC7ylJFkJ8LTAQF8AFvy2kBSFjt49Xqw9qjJKOreKCswWxeKoFEMIWZgNJHlo+gsw1N90oFSxx54Tpb34ZPjSiZqxhgBRGs8cTogvLh+Ko09mTWELCSeKM891ZjcsEyYYN0G1wlf0S7s91SiMyl2ltXhOo/orlhguIRbOR5hpFfgpcGFlqmSGN2BRdps4GAP/3i7xVmIyAEVkMEzQwEfcFdoGddEgfOuE1E3By8NZHlyGdy8woJWidzLSdwepvGkjsEDphDwrWkAB2dkQ55fBZ5kOI/mIuY7NtlZZzVxhpOVVBZhm8OJRTe6aM3+yMOf+jgGy3RDMavYDVtu6Dv0SBfLsNkMZtC5IcI5vVOWFcgwWS6YdlZUuS6/VFwXaCVe0NN user1 ansible-target)
    
    displayName: 'Run Python and set pipeline variable'

  # 4) Use the variable
  - bash: |
      echo "ALIAS: $(ALIAS)"
      echo "IP: $(IP)"
      echo "USER: $(USER)"
      echo "PASSWORD: $(PASSWORD)"
    displayName: 'Use the Python value'

  - script: |
      set -e
      sudo apt-get update -y
      sudo apt-get install -y sshpass

      export SSHPASS="$(MY_SECRET)"

      # Run one command via SSH using password from secret variable
      sshpass -e ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -p $(SSH_PORT) \
        $(SSH_USER)@$(SSH_HOST) "$(REMOTE_CMD)"
        
    displayName: 'SSH with password variable and run one command'
  
